# Generated by Django 4.2.28 on 2026-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userregistrationmodel_profile_image_videoanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
