# Generated by Django 4.2.28 on 2026-06-07 03:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_videoanalysis_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoanalysis',
            name='metrics',
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='input_video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/input/'),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='output_video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/output/'),
        ),
    ]
